// apps/pear/src/app/app.tsx
import React from 'react';
import { dog } from '@nx-demo/dog';
import { cat } from '@nx-demo/cat';
import { AdsLayout, AdsLayoutAside, AdsLayoutContent } from '@nx-demo/ads-react';

import './app.scss';

export const App = () => {
  return (
    <AdsLayout>
      <AdsLayoutAside>
        <div className="text-center">
          <h2>
            pear
          </h2>
          <p className="lead">
            <em>React 16.x</em>
          </p>
        </div>
        <ul className="nav nav-pills flex-column">
          <li className="nav-item">
            <a href="/apple" className="nav-link">
              Apple
            </a>
          </li>
          <li className="nav-item">
            <a href="/orange" className="nav-link">
              Orange
            </a>
          </li>
          <li className="nav-item">
            <a href="/pear" className="nav-link active">
              Pear
            </a>
          </li>
        </ul>
      </AdsLayoutAside>
      <AdsLayoutContent>
        <ul className="animals list-unstyled">
          {[dog, cat].map(a => <li key={a}>{a}</li>)}
        </ul>
        <button className="btn btn-primary">
          Done
        </button>
      </AdsLayoutContent>
    </AdsLayout>
  );
};

export default App;

// apps/apple/src/app/app.component.ts
import { Component } from '@angular/core';
import { cat } from '@nx-demo/cat';
import { dog } from '@nx-demo/dog';

@Component({
  selector: 'nx-demo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'apple';
  animals = [dog, cat];
}

<ads-layout>

  <ads-layout-aside>

    <div class="text-center">

      <h2>
        {{ title }}
      </h2>

      <p class="lead">
        <em>Angular 8.x</em>
      </p>

    </div>

    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a href="/apple" class="nav-link active">
          Apple
        </a>
      </li>
      <li class="nav-item">
        <a href="/orange" class="nav-link">
          Orange
        </a>
      </li>
      <li class="nav-item">
        <a href="/pear" class="nav-link">
          Pear
        </a>
      </li>
    </ul>

  </ads-layout-aside>

  <ads-layout-content>

    <ul class="animals list-unstyled">
      <li *ngFor="let animal of animals">
        {{ animal }}
      </li>
    </ul>

    <button class="btn btn-primary">
      Done
    </button>

    <nx-demo-post-list-container></nx-demo-post-list-container>

    <router-outlet></router-outlet>

  </ads-layout-content>

</ads-layout>
